name: Application Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/app-pipeline.yml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPOSITORY_URL: ${{ vars.ECR_REPOSITORY_URL }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t "$ECR_REPOSITORY_URL:${{ github.sha }}" \
            ./app

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ env.ECR_REPOSITORY_URL }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Push Docker image to ECR
        run: |
          docker push \
            "$ECR_REPOSITORY_URL:${{ github.sha }}"
